name: "poetry"
description: "Install poetry"

runs:
  using: composite

  steps:
    - name: "Install poetry"
      run: curl -sSL https://install.python-poetry.org | python - -y
      shell: bash

    - name: "Add poetry to PATH (Ubuntu/Mac)"
      if: ${{ matrix.os != 'windows-latest' }}
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: "Add poetry to PATH (Windows)"
      if: ${{ matrix.os == 'windows-latest' }}
      run: echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH
      shell: bash

    - name: "Configure poetry"
      run: poetry config virtualenvs.in-project true
      shell: bash
