name: Docs

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
      poetry-version:
        required: false
        type: string
        default: "1.7.1"
      os:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  submit-docs:
    runs-on: ${{ inputs.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - uses: MrThearMan/CI/.github/actions/poetry@v0.4.3
        with:
          os: ${{ inputs.os }}
          poetry-version: ${{ inputs.poetry-version }}

      - name: "Load cached poetry environment"
        uses: actions/cache@v3
        with:
          path: .venv
          key: cache-v1-docs-python${{ steps.setup-python.outputs.python-version }}-${{ inputs.os }}

      - name: "Install dependencies"
        run: poetry install

      - name: "Deploy docs"
        run: poetry run mkdocs gh-deploy --force --strict --verbose
