name: Docs

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.14"
      uv-version:
        required: false
        type: string
        default: "0.12.10"
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      env:
        required: false
        type: string
        default: '{}'
      submodules:
        required: false
        type: boolean
        default: false
      fetch-depth:
        required: false
        type: number
        default: 1
      uv-cache-suffix:
        required: false
        type: string
        default: ""

jobs:
  submit-docs:
    runs-on: ${{ inputs.os }}
    env: ${{ fromJSON(inputs.env) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v7
        with:
          submodules: ${{ inputs.submodules }}
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ inputs.uv-version }}
          python-version: ${{ inputs.python-version }}
          enable-cache: true
          cache-suffix: ${{ inputs.uv-cache-suffix }}

      - name: "Install dependencies"
        run: uv sync --locked --group docs

      - name: "Deploy docs"
        run: uv run mkdocs gh-deploy --force --strict --verbose
