name: Docs

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.13"
      poetry-version:
        required: false
        type: string
        default: "2.1.2"
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      submodules:
        required: false
        type: boolean
        default: false
      fetch-depth:
        required: false
        type: number
        default: 1

jobs:
  submit-docs:
    runs-on: ${{ inputs.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: "Set up python"
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: MrThearMan/CI/.github/actions/poetry@v0.4.14
        with:
          os: ${{ inputs.os }}
          poetry-version: ${{ inputs.poetry-version }}
          python-version: ${{ steps.setup-python.outputs.python-version }}

      - name: "Load cached poetry environment"
        uses: actions/cache@v4
        with:
          path: .venv
          key: cache-v1-docs-python${{ steps.setup-python.outputs.python-version }}-${{ inputs.os }}

      - name: "Install dependencies"
        run: poetry install

      - name: "Deploy docs"
        run: poetry run mkdocs gh-deploy --force --strict --verbose
