name: Release

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
      poetry-version:
        required: false
        type: string
        default: "1.3.1"
    secrets:
      pypi-token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Install poetry"
        run: pipx install "poetry==${{ inputs.poetry-version }}"

      - name: "Set up python"
        uses: actions/setup-python@v4
        with:
          cache: "poetry"
          python-version: ${{ inputs.python-version }}

      - name: "Pre-release hook"
        if: ${{ hashFiles('.github/actions/pre-release/action.yml') != '' }}
        uses: ./.github/actions/pre-release

      - name: "Install dependencies"
        run: poetry install

      - name: "Publish on PyPi"
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi-token }}

      - name: "Post-release hook"
        if: ${{ hashFiles('.github/actions/post-release/action.yml') != '' }}
        uses: ./.github/actions/post-release
