name: Release

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.14"
      uv-version:
        required: false
        type: string
        default: "0.12.10"
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      env:
        required: false
        type: string
        default: '{}'
      submodules:
        required: false
        type: boolean
        default: false
      fetch-depth:
        required: false
        type: number
        default: 1
      uv-cache-suffix:
        required: false
        type: string
        default: ""
    secrets:
      pypi-token:
        required: true

jobs:
  publish:
    runs-on: ${{ inputs.os }}
    env: ${{ fromJSON(inputs.env) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6
        with:
          submodules: ${{ inputs.submodules }}
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ inputs.uv-version }}
          python-version: ${{ inputs.python-version }}
          enable-cache: true
          cache-suffix: ${{ inputs.uv-cache-suffix }}

      - name: "Pre-release hook"
        if: ${{ hashFiles('.github/actions/pre-release/action.yml') != '' }}
        uses: ./.github/actions/pre-release

      - name: "Test that project version matches release version"
        run: |
          echo "Project version: '$(uv version --short)'"
          echo "Release version: '$(echo ${{ github.event.release.tag_name }} | tr -d 'v')'"
          test $(uv version --short) == $(echo ${{ github.event.release.tag_name }} | tr -d 'v')

      - name: "Build distributions"
        run: uv build

      - name: "Publish on PyPi"
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.pypi-token }}

      - name: "Post-release hook"
        if: ${{ hashFiles('.github/actions/post-release/action.yml') != '' }}
        uses: ./.github/actions/post-release
