name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '["3.11", "3.12", "3.13", "3.14"]'
      os:
        required: false
        type: string
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      env:
        required: false
        type: string
        default: '{}'
      uv-version:
        required: false
        type: string
        default: "0.12.10"
      exclude:
        required: false
        type: string
        default: '[{"os": "none", "python-version": "none"}]'
      submodules:
        required: false
        type: boolean
        default: false
      fetch-depth:
        required: false
        type: number
        default: 1
      coveralls:
        required: false
        type: boolean
        default: true
      coveralls-os:
        required: false
        type: string
        default: "ubuntu-latest"
      uv-cache-suffix:
        required: false
        type: string
        default: ""

jobs:
  test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env: ${{ fromJSON(inputs.env) }}

    # Cancel old workflows when a new workflow is triggered for the same PR/branch/tag & python version & OS & environment.
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.python-version }}-${{ matrix.os }}-${{ inputs.env }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        python-version: ${{ fromJSON(inputs.python-version) }}
        exclude: ${{ fromJSON(inputs.exclude) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v7
        with:
          submodules: ${{ inputs.submodules }}
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: "Set up python"
        id: setup-python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ inputs.uv-version }}
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: ${{ inputs.uv-cache-suffix }}

      - name: "Load cached nox environment"
        uses: actions/cache@v6
        id: nox-cache
        with:
          path: .nox
          key: cache-v1-nox-python${{ steps.setup-python.outputs.python-version }}-${{ matrix.os }}-${{ hashFiles('**/uv.lock') }}

      - name: "Pre-test hook"
        if: ${{ hashFiles('.github/actions/pre-test/action.yml') != '' }}
        uses: ./.github/actions/pre-test

      - name: "Run tests with nox"
        run: uvx nox --session tests --python ${{ matrix.python-version }}

      - name: "Make coverage report"
        if: ${{ inputs.coveralls && inputs.coveralls-os == matrix.os }}
        run: |
          uvx coverage report
          uvx coverage xml

      - name: "Post-test hook"
        if: ${{ hashFiles('.github/actions/post-test/action.yml') != '' }}
        uses: ./.github/actions/post-test

      - name: "Submit coverage"
        if: ${{ inputs.coveralls && inputs.coveralls-os == matrix.os }}
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.xml
          flag-name: ${{ steps.setup-python.outputs.python-version }}-${{ matrix.os }}
          parallel: true

  submit-coverage:
    needs: test
    runs-on: ${{ inputs.coveralls-os }}
    env: ${{ fromJSON(inputs.env) }}
    if: ${{ inputs.coveralls }}
    steps:
      - name: "Finnish coverage report"
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
