name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
      os:
        required: false
        type: string
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      poetry-version:
        required: false
        type: string
        default: "1.4.1"
      submit-python-version:
        required: false
        type: string
        default: "3.11"
      submit-os:
        required: false
        type: string
        default: "ubuntu-latest"
      exclude:
        required: false
        type: string
        default: '[{"os": "none", "python-version": "none"}]'

jobs:
  test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        python-version: ${{ fromJSON(inputs.python-version) }}
        exclude: ${{ fromJSON(inputs.exclude) }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Install poetry"
        run: pipx install "poetry==${{ inputs.poetry-version }}"

      - name: "Set up python"
        id: setup-python
        uses: actions/setup-python@v4
        with:
          cache: "poetry"
          python-version: ${{ matrix.python-version }}

      - name: "Load cached tox environment"
        uses: actions/cache@v3
        with:
          path: .tox
          key: cache-v1-python${{ steps.setup-python.outputs.python-version }}-${{ matrix.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: "Pre-test hook"
        if: ${{ hashFiles('.github/actions/pre-test/action.yml') != '' }}
        uses: ./.github/actions/pre-test

      - name: "Install dependencies"
        run: poetry install

      - name: "Run tox"
        run: poetry run tox

      - name: "Post-test hook"
        if: ${{ hashFiles('.github/actions/post-test/action.yml') != '' }}
        uses: ./.github/actions/post-test

      - name: "Submit coverage"
        run: poetry run coveralls --service=github
        env:
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}-${{ matrix.os }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit-coverage:
    needs: test
    runs-on: ${{ inputs.submit-os }}

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Install poetry"
        run: pipx install "poetry==${{ inputs.poetry-version }}"

      - name: "Set up python"
        uses: actions/setup-python@v4
        with:
          cache: "poetry"
          python-version: ${{ inputs.submit-python-version }}

      - name: "Install dependencies"
        run: poetry install

      - name: "Finnish coverage report"
        run: poetry run coveralls --service=github --finish
        env:
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
